# Generated by Django 5.2.17 on 2026-08-19 06:47

import dawak_compare.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DawakCompareRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("dawak_file_name", models.CharField(max_length=255)),
                ("hiba_file_name", models.CharField(max_length=255)),
                ("pharmacies_count", models.IntegerField(default=0)),
                ("matched_count", models.IntegerField(default=0)),
                ("mismatched_count", models.IntegerField(default=0)),
                (
                    "mismatched_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "hiba_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=dawak_compare.models.upload_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية مطابقة دواك",
                "verbose_name_plural": "عمليات مطابقة دواك",
                "ordering": ["-created_at"],
            },
        ),
    ]
