# Generated by Django 5.2.17 on 2026-08-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dawak_compare", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dawakcomparerun",
            name="payments_dawak_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dawakcomparerun",
            name="payments_found_diff_date_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="dawakcomparerun",
            name="payments_found_diff_date_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dawakcomparerun",
            name="payments_hiba_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dawakcomparerun",
            name="payments_matched_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dawakcomparerun",
            name="payments_true_diff_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="dawakcomparerun",
            name="payments_true_diff_count",
            field=models.IntegerField(default=0),
        ),
    ]
