# Generated by Django 5.2.17 on 2026-09-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dawak_compare", "0002_dawakcomparerun_payments_dawak_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dawakcomparerun",
            name="cc_matched_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dawakcomparerun",
            name="cc_mismatched_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dawakcomparerun",
            name="cc_no_hiba_data_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dawakcomparerun",
            name="cc_unresolved_hiba_rows",
            field=models.IntegerField(default=0),
        ),
    ]
