# Generated by Django 5.2.17 on 2026-10-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_moduleaccess_module_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moduleaccess",
            name="module_code",
            field=models.CharField(
                choices=[
                    ("reconciliation_hs", "مطابقة هبة - سدانة"),
                    ("commissions", "عمولات المندوبين"),
                    ("distributor_commissions", "عمولة تحصيل الموزعين الداخليين"),
                    ("data_cleaning", "تنظيف داتا"),
                    ("tax_inventory", "مطابقة جرد الضريبة"),
                    ("dawak_compare", "مطابقة دواك"),
                    ("account_statement", "فصل كشف الحساب (ليرة/دولار)"),
                    ("compensation", "تعويضات فيتا فارما"),
                    ("external_commissions", "عمولات الموزعين الخارجيين"),
                    (
                        "argivit_compare",
                        "مطابقة أسعار الارجيفيت والمبيعات مع المرتجعات",
                    ),
                ],
                max_length=50,
            ),
        ),
    ]
