# Generated by Django 5.2.17 on 2026-08-19 07:05

import compensation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompensationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_file_name", models.CharField(max_length=255)),
                ("raw_row_count", models.IntegerField(default=0)),
                ("cancelled_pairs", models.IntegerField(default=0)),
                ("items_count", models.IntegerField(default=0)),
                ("eligible_rows", models.IntegerField(default=0)),
                ("flagged_rows", models.IntegerField(default=0)),
                (
                    "total_gifts",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_claim_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True, null=True, upload_to=compensation.models.upload_path
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية تعويضات فيتا فارما",
                "verbose_name_plural": "عمليات تعويضات فيتا فارما",
                "ordering": ["-created_at"],
            },
        ),
    ]
