# Generated by Django 5.2.17 on 2026-08-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationrun",
            name="excluded_rows",
            field=models.IntegerField(default=0),
        ),
    ]
