# Generated by Django 5.2.17 on 2026-08-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0002_compensationrun_excluded_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationrun",
            name="retail_fallback_claim_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="retail_fallback_rows",
            field=models.IntegerField(default=0),
        ),
    ]
