# Generated by Django 5.2.17 on 2026-08-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0003_compensationrun_retail_fallback_claim_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationrun",
            name="total_pharmacy_offer_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
