# Generated by Django 5.2.17 on 2026-08-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0004_compensationrun_total_pharmacy_offer_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationrun",
            name="customer_groups_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="gifts_fallback_claim_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="gifts_fallback_rows",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="ineligible_groups_count",
            field=models.IntegerField(default=0),
        ),
    ]
