# Generated by Django 5.2.17 on 2026-08-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0005_compensationrun_customer_groups_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compensationrun",
            name="customer_groups_count",
        ),
        migrations.RemoveField(
            model_name="compensationrun",
            name="eligible_rows",
        ),
        migrations.RemoveField(
            model_name="compensationrun",
            name="excluded_rows",
        ),
        migrations.RemoveField(
            model_name="compensationrun",
            name="flagged_rows",
        ),
        migrations.RemoveField(
            model_name="compensationrun",
            name="gifts_fallback_claim_value",
        ),
        migrations.RemoveField(
            model_name="compensationrun",
            name="gifts_fallback_rows",
        ),
        migrations.RemoveField(
            model_name="compensationrun",
            name="retail_fallback_claim_value",
        ),
        migrations.RemoveField(
            model_name="compensationrun",
            name="retail_fallback_rows",
        ),
        migrations.RemoveField(
            model_name="compensationrun",
            name="total_pharmacy_offer_value",
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="groups_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="ignored_items_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="offer_row_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="total_qty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="unmatched_returns_count",
            field=models.IntegerField(default=0),
        ),
    ]
