# Generated by Django 5.2.17 on 2026-08-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0007_compensationrun_total_formula_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationrun",
            name="cancelled_mabee_pairs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="excluded_mabee_rows_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="excluded_zero_qty_rows_count",
            field=models.IntegerField(default=0),
        ),
    ]
