# Generated by Django 5.2.17 on 2026-08-31 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0008_compensationrun_cancelled_mabee_pairs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compensationrun",
            name="excluded_zero_qty_rows_count",
        ),
    ]
