# Generated by Django 5.2.17 on 2026-08-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0009_remove_compensationrun_excluded_zero_qty_rows_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationrun",
            name="excluded_nonpositive_rows_count",
            field=models.IntegerField(default=0),
        ),
    ]
