# Generated by Django 5.2.17 on 2026-08-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0010_compensationrun_excluded_nonpositive_rows_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationrun",
            name="merged_zero_qty_rows_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="unmerged_zero_qty_rows_count",
            field=models.IntegerField(default=0),
        ),
    ]
