# Generated by Django 5.2.17 on 2026-10-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0011_compensationrun_merged_zero_qty_rows_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationrun",
            name="pool_matched_rows_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="compensationrun",
            name="pool_matches_count",
            field=models.IntegerField(default=0),
        ),
    ]
