# Generated by Django 5.2.17 on 2026-10-01 10:30

import argivit_compare.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArgivitCompareRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("movement_file_name", models.CharField(max_length=255)),
                ("price_file_name", models.CharField(max_length=255)),
                ("ledger_file_name", models.CharField(max_length=255)),
                (
                    "wholesale_file_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("rate_mode", models.CharField(default="fixed", max_length=10)),
                (
                    "rate_lo",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                (
                    "rate_hi",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("movement_rows_count", models.IntegerField(default=0)),
                ("tier1_count", models.IntegerField(default=0)),
                ("tier2_count", models.IntegerField(default=0)),
                ("tier3_count", models.IntegerField(default=0)),
                ("tier4_count", models.IntegerField(default=0)),
                ("unmatched_count", models.IntegerField(default=0)),
                ("retail_matched_count", models.IntegerField(default=0)),
                ("retail_mismatched_count", models.IntegerField(default=0)),
                ("wholesale_matched_count", models.IntegerField(default=0)),
                ("wholesale_mismatched_count", models.IntegerField(default=0)),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=argivit_compare.models.upload_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية مطابقة أسعار الارجيفيت",
                "verbose_name_plural": "عمليات مطابقة أسعار الارجيفيت",
                "ordering": ["-created_at"],
            },
        ),
    ]
