# Generated by Django 5.2.17 on 2026-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("argivit_compare", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="argivitcomparerun",
            name="retail_no_counterpart_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="argivitcomparerun",
            name="wholesale_no_counterpart_count",
            field=models.IntegerField(default=0),
        ),
    ]
