# Generated by Django 5.2.17 on 2026-08-19 06:50

import django.db.models.deletion
import external_commissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCommissionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("distributors_count", models.IntegerField(default=0)),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=external_commissions.models.upload_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية عمولات موزعين خارجيين",
                "verbose_name_plural": "عمليات عمولات الموزعين الخارجيين",
                "ordering": ["-created_at"],
            },
        ),
    ]
