# Generated by Django 5.2.17 on 2026-08-19 06:42

import django.db.models.deletion
import tax_inventory.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxInventoryRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("over3_file_name", models.CharField(max_length=255)),
                ("under3_file_name", models.CharField(max_length=255)),
                ("sales_file_name", models.CharField(max_length=255)),
                ("items_over3", models.IntegerField(default=0)),
                ("items_matched_in_sales", models.IntegerField(default=0)),
                (
                    "total_inventory_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "total_sold_qty",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("total_final_qty", models.IntegerField(default=0)),
                ("cross_listed_count", models.IntegerField(default=0)),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=tax_inventory.models.upload_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية مطابقة جرد",
                "verbose_name_plural": "عمليات مطابقة الجرد",
                "ordering": ["-created_at"],
            },
        ),
    ]
