# Generated by Django 5.2.17 on 2026-08-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tax_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taxinventoryrun",
            name="approx_items_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="taxinventoryrun",
            name="capped_items_count",
            field=models.IntegerField(default=0),
        ),
    ]
