# Generated by Django 5.2.17 on 2026-08-22 08:15

import distributor_commissions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributorCommissionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ledger_file_name", models.CharField(blank=True, max_length=255)),
                ("distributors_count", models.IntegerField(default=0)),
                ("rows_count", models.IntegerField(default=0)),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total_commission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=distributor_commissions.models.upload_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية عمولة تحصيل موزعين",
                "verbose_name_plural": "عمليات عمولة تحصيل الموزعين",
                "ordering": ["-created_at"],
            },
        ),
    ]
