# Generated by Django 5.2.17 on 2026-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("distributor_commissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorcommissionrun",
            name="collection_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="distributorcommissionrun",
            name="flagged_rows_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="distributorcommissionrun",
            name="return_rows_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="distributorcommissionrun",
            name="return_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="distributorcommissionrun",
            name="warehouse_excluded_count",
            field=models.IntegerField(default=0),
        ),
    ]
