# Generated by Django 5.2.17 on 2026-09-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "distributor_commissions",
            "0002_distributorcommissionrun_collection_total_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorcommissionrun",
            name="fuzzy_biyad_rows_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="distributorcommissionrun",
            name="unresolved_rows_count",
            field=models.IntegerField(default=0),
        ),
    ]
