# Generated by Django 5.2.17 on 2026-08-19 06:54

import data_cleaning.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataCleaningRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("total_rows", models.IntegerField(default=0)),
                ("sales_rows", models.IntegerField(default=0)),
                ("returns_rows", models.IntegerField(default=0)),
                ("receivables_rows", models.IntegerField(default=0)),
                ("discount_rows", models.IntegerField(default=0)),
                (
                    "total_deferred_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=data_cleaning.models.upload_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية تنظيف داتا",
                "verbose_name_plural": "عمليات تنظيف الداتا",
                "ordering": ["-created_at"],
            },
        ),
    ]
