# Generated by Django 5.2.17 on 2026-08-19 06:42

import account_statement.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatementSplitRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_file_name", models.CharField(max_length=255)),
                ("total_rows", models.IntegerField(default=0)),
                ("summary_json", models.JSONField(blank=True, default=dict)),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=account_statement.models.upload_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية فصل عملات",
                "verbose_name_plural": "عمليات فصل العملات",
                "ordering": ["-created_at"],
            },
        ),
    ]
