# Generated by Django 5.2.17 on 2026-08-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commissionrun",
            name="total_collection_commission",
        ),
    ]
