# Generated by Django 5.2.17 on 2026-08-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0002_remove_commissionrun_total_collection_commission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commissionrun",
            name="total_returns_deduction",
        ),
    ]
