# Generated by Django 5.2.17 on 2026-09-27 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissions", "0003_remove_commissionrun_total_returns_deduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionrun",
            name="additions_missing_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="commissionrun",
            name="additions_unmatched_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="commissionrun",
            name="additions_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="commissionrun",
            name="total_due",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="commissionrun",
            name="total_net",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
