# Generated by Django 5.2.17 on 2026-08-19 06:27

import django.db.models.deletion
import reconciliation_hs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("hiba_file_name", models.CharField(max_length=255)),
                ("sadana_file_name", models.CharField(max_length=255)),
                ("hiba_count", models.IntegerField(default=0)),
                ("sadana_count", models.IntegerField(default=0)),
                ("matched_count", models.IntegerField(default=0)),
                ("matched_same_day", models.IntegerField(default=0)),
                ("matched_date_diff", models.IntegerField(default=0)),
                ("hiba_only_count", models.IntegerField(default=0)),
                ("sadana_only_count", models.IntegerField(default=0)),
                (
                    "hiba_only_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "sadana_only_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                ("hiba_period_start", models.DateField(blank=True, null=True)),
                ("hiba_period_end", models.DateField(blank=True, null=True)),
                ("sadana_period_start", models.DateField(blank=True, null=True)),
                ("sadana_period_end", models.DateField(blank=True, null=True)),
                ("has_errors", models.BooleanField(default=False)),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=reconciliation_hs.models.upload_path,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية مطابقة",
                "verbose_name_plural": "عمليات المطابقة",
                "ordering": ["-created_at"],
            },
        ),
    ]
