# Generated by Django 5.2.17 on 2026-08-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reconciliation_hs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reconciliationrun",
            name="found_diff_date_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name="reconciliationrun",
            name="found_diff_date_count",
            field=models.IntegerField(default=0),
        ),
    ]
