# Generated by Django 5.2.17 on 2026-08-19 06:47

import django.db.models.deletion
import receivables.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivablesRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_file_name", models.CharField(max_length=255)),
                ("total_rows", models.IntegerField(default=0)),
                ("linked_rows", models.IntegerField(default=0)),
                ("unlinked_rows", models.IntegerField(default=0)),
                ("groups_count", models.IntegerField(default=0)),
                ("matched_groups", models.IntegerField(default=0)),
                ("mismatched_groups", models.IntegerField(default=0)),
                (
                    "mismatched_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=18),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True, null=True, upload_to=receivables.models.upload_path
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "عملية مطابقة ذمم",
                "verbose_name_plural": "عمليات مطابقة الذمم",
                "ordering": ["-created_at"],
            },
        ),
    ]
