# Generated by Django 5.2.17 on 2026-09-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receivables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivablesrun",
            name="name_linked_groups",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="receivablesrun",
            name="persons_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="receivablesrun",
            name="shared_mismatched_groups",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="receivablesrun",
            name="solo_mismatched_groups",
            field=models.IntegerField(default=0),
        ),
    ]
